apiVersion: "sparkoperator.hpe.com/v1beta2"
kind: SparkApplication
metadata:
  name: "spark-etl"
spec:
  sparkConf:
    spark.hadoop.fs.s3a.path.style.access: "true"
    spark.hadoop.fs.s3a.impl: "org.apache.hadoop.fs.s3a.S3AFileSystem"
    spark.hadoop.fs.s3a.connection.ssl.enabled: "false"
    spark.mapr.extraconf.secret: {{dag_run.conf.get("s3_secret_name", "spark-s3-creds")}} 
    spark.hadoop.fs.s3a.s3.client.factory.impl: org.apache.hadoop.fs.s3a.NonChunkedDefaultS3ClientFactory
    spark.driver.extraClassPath: /mnt/shared/spark/disable-chunk-encoding-334.jar
    spark.executor.extraClassPath: /mnt/shared/spark/disable-chunk-encoding-334.jar
    spark.hadoop.fs.s3a.bucket.ezua-demo.endpoint: http://local-s3-service.ezdata-system.svc.cluster.local:30000
    spark.driver.cores": 2,
    spark.executor.cores": 2,
    spark.executor.cores": 2,
    spark.driver.memory": "1000M",
    spark.executor.memory": "1000M",
    spark.ssl.enabled": false,
    spark.kubernetes.driver.volumes.persistentVolumeClaim.pv1.options.claimName": "kubeflow-shared-pvc",
    spark.kubernetes.driver.volumes.persistentVolumeClaim.pv1.mount.path": "/mounts/shared-volume/shared",
    spark.kubernetes.driver.volumes.persistentVolumeClaim.pv1.mount.readOnly": false,
    spark.kubernetes.executor.volumes.persistentVolumeClaim.pv1.options.claimName": "kubeflow-shared-pvc",
    spark.kubernetes.executor.volumes.persistentVolumeClaim.pv1.mount.path": "/mounts/shared-volume/shared",
    spark.kubernetes.executor.volumes.persistentVolumeClaim.pv1.mount.readOnly": false,
    spark.kubernetes.driver.volumes.persistentVolumeClaim.upv1.options.claimName": "ezadmin-spark-pvc",
    spark.kubernetes.driver.volumes.persistentVolumeClaim.upv1.mount.path": "/mounts/shared-volume/user",
    spark.kubernetes.driver.volumes.persistentVolumeClaim.upv1.mount.readOnly": false,
    spark.kubernetes.executor.volumes.persistentVolumeClaim.upv1.options.claimName": "ezadmin-spark-pvc",
    spark.kubernetes.executor.volumes.persistentVolumeClaim.upv1.mount.path": "/mounts/shared-volume/user",
    spark.kubernetes.executor.volumes.persistentVolumeClaim.upv1.mount.readOnly": false,
    spark.dynamicAllocation.enabled": true,
    spark.dynamicAllocation.shuffleTracking.enabled": true,
    spark.dynamicAllocation.minExecutors": 1,
    spark.dynamicAllocation.maxExecutors": 4,
    spark.kubernetes.container.image": "gcr.io/mapr-252711/spark-3.4.0:v3.4.0",
    spark.kubernetes.container.image.pullPolicy": "Always",
    spark.sql.extensions": "io.delta.sql.DeltaSparkSessionExtension",
    spark.sql.catalog.spark_catalog": "org.apache.spark.sql.delta.catalog.DeltaCatalog",
    spark.executor.extraJavaOptions": "-Dcom.amazonaws.sdk.disableCertChecking=true",
    spark.driver.extraJavaOptions": "-Dcom.amazonaws.sdk.disableCertChecking=true",
    spark.hadoop.fs.s3a.path.style.access": true,
    spark.hadoop.fs.s3a.impl": "org.apache.hadoop.fs.s3a.S3AFileSystem",
    spark.hadoop.fs.s3a.access.key": "PO93KAAP2YTG4RHMG499FENAFWYUH9Q91XOJYQ6UNY4R0XUVY35A53L47",
    spark.hadoop.fs.s3a.secret.key": "UV0H7MFJI96MCFY03IMD9X6ZT8H43B3GDS8SXGA4Z7FH0QT2DSZV3ZCKTHS93Z",
    spark.hadoop.fs.s3a.endpoint": "https://54.251.141.200:9000",
    spark.kubernetes.driverEnv.PRESTO_ACCESS_TOKEN": "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJwNTdWNHFEVldrTlp6Zkw4Z0h1STNmRHdtTFQ0VjlMN05wWDFMWkdOWjg4In0.eyJleHAiOjE3MDE4NDg5ODIsImlhdCI6MTcwMTI0NDE4MiwiYXV0aF90aW1lIjoxNzAxMjQ0MTgyLCJqdGkiOiI4YTlhNTQ5Zi0zNWUwLTRjOWEtYTllMS00OTdjMDIzNDE5NTMiLCJpc3MiOiJodHRwczovL2tleWNsb2FrLnRydWVwb2MuZXphcGFjLmNvbS9yZWFsbXMvVUEiLCJhdWQiOiJ1YSIsInN1YiI6ImI5OWNhZTAwLThmZjYtNDRmYy1hNmRhLWJjNWNhNTY2ZDJhNyIsInR5cCI6IklEIiwiYXpwIjoidWEiLCJub25jZSI6Ill2ckxxbW1GZGw2eFRmMnk4bGRzM0FUbkxFWV9oM2ZJUWNVb0JPcUFPVTQiLCJzZXNzaW9uX3N0YXRlIjoiMTBiMjMyMDktNmM0OS00NWMyLTljMTMtZGZlZTAyZDJjNzU0IiwiYXRfaGFzaCI6Ik5DdXFCeVhoOXB3aEJaSlkxeUhNRVEiLCJhY3IiOiIxIiwic2lkIjoiMTBiMjMyMDktNmM0OS00NWMyLTljMTMtZGZlZTAyZDJjNzU0IiwidWlkIjoiNjAwMCIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZ2lkIjoiNTAwNSIsIm5hbWUiOiJFem1lcmFsIEFkbWluaXN0cmF0b3IiLCJncm91cHMiOlsidWEtZW5hYmxlZCIsIm9mZmxpbmVfYWNjZXNzIiwiYWRtaW4iLCJ1bWFfYXV0aG9yaXphdGlvbiIsImRlZmF1bHQtcm9sZXMtdWEiXSwicHJlZmVycmVkX3VzZXJuYW1lIjoiZXphZG1pbiIsImdpdmVuX25hbWUiOiJFem1lcmFsIiwicG9zaXhfdXNlcm5hbWUiOiJlemFkbWluIiwiZmFtaWx5X25hbWUiOiJBZG1pbmlzdHJhdG9yIiwiZW1haWwiOiJlemFkbWluQGV6YXBhYy5jb20ifQ.K04_wCCp5RC6URybAP8EMMaGxnmU1q2MyMzzE3jzUQoaJCnnBQoW_TXfKFyWtnIzcrW55OXeH1vAJmbstYg3Ubj22rT1BocRMgdADJ4taLjBtnQk9H98UxHGDXOrwurhFdalkc8uigXqJnUq6UrKWTd1ChRSjW4cvIU1fUw9vthWlIbSOJeaYmhcEaVEDiXIw2B8nqhKQIndf0lVr3_A-YzLgPx8jmB-Hb45-Yqtj2CWCNafQJGvs9V5LL-DbJIuaKQXH1Gzha7Mmlg6Ua_2s5ZylCSBA_zEZKd91OlMxjAxFioj0bdpiRy6YuI5f6mhlBqovZdZj1xSAi65uQpqew",
    spark.executorEnv.PRESTO_ACCESS_TOKEN": "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJwNTdWNHFEVldrTlp6Zkw4Z0h1STNmRHdtTFQ0VjlMN05wWDFMWkdOWjg4In0.eyJleHAiOjE3MDE4NDg5ODIsImlhdCI6MTcwMTI0NDE4MiwiYXV0aF90aW1lIjoxNzAxMjQ0MTgyLCJqdGkiOiI4YTlhNTQ5Zi0zNWUwLTRjOWEtYTllMS00OTdjMDIzNDE5NTMiLCJpc3MiOiJodHRwczovL2tleWNsb2FrLnRydWVwb2MuZXphcGFjLmNvbS9yZWFsbXMvVUEiLCJhdWQiOiJ1YSIsInN1YiI6ImI5OWNhZTAwLThmZjYtNDRmYy1hNmRhLWJjNWNhNTY2ZDJhNyIsInR5cCI6IklEIiwiYXpwIjoidWEiLCJub25jZSI6Ill2ckxxbW1GZGw2eFRmMnk4bGRzM0FUbkxFWV9oM2ZJUWNVb0JPcUFPVTQiLCJzZXNzaW9uX3N0YXRlIjoiMTBiMjMyMDktNmM0OS00NWMyLTljMTMtZGZlZTAyZDJjNzU0IiwiYXRfaGFzaCI6Ik5DdXFCeVhoOXB3aEJaSlkxeUhNRVEiLCJhY3IiOiIxIiwic2lkIjoiMTBiMjMyMDktNmM0OS00NWMyLTljMTMtZGZlZTAyZDJjNzU0IiwidWlkIjoiNjAwMCIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZ2lkIjoiNTAwNSIsIm5hbWUiOiJFem1lcmFsIEFkbWluaXN0cmF0b3IiLCJncm91cHMiOlsidWEtZW5hYmxlZCIsIm9mZmxpbmVfYWNjZXNzIiwiYWRtaW4iLCJ1bWFfYXV0aG9yaXphdGlvbiIsImRlZmF1bHQtcm9sZXMtdWEiXSwicHJlZmVycmVkX3VzZXJuYW1lIjoiZXphZG1pbiIsImdpdmVuX25hbWUiOiJFem1lcmFsIiwicG9zaXhfdXNlcm5hbWUiOiJlemFkbWluIiwiZmFtaWx5X25hbWUiOiJBZG1pbmlzdHJhdG9yIiwiZW1haWwiOiJlemFkbWluQGV6YXBhYy5jb20ifQ.K04_wCCp5RC6URybAP8EMMaGxnmU1q2MyMzzE3jzUQoaJCnnBQoW_TXfKFyWtnIzcrW55OXeH1vAJmbstYg3Ubj22rT1BocRMgdADJ4taLjBtnQk9H98UxHGDXOrwurhFdalkc8uigXqJnUq6UrKWTd1ChRSjW4cvIU1fUw9vthWlIbSOJeaYmhcEaVEDiXIw2B8nqhKQIndf0lVr3_A-YzLgPx8jmB-Hb45-Yqtj2CWCNafQJGvs9V5LL-DbJIuaKQXH1Gzha7Mmlg6Ua_2s5ZylCSBA_zEZKd91OlMxjAxFioj0bdpiRy6YuI5f6mhlBqovZdZj1xSAi65uQpqew"

  type: Python
  sparkVersion: 3.4.1
  mode: cluster
  image: "gcr.io/mapr-252711/spark-py-3.4.1:v3.4.1"
  imagePullPolicy: Always
  mainApplicationFile: "local:///mnt/shared/spark/hive_dataload.py"
  restartPolicy:
    type: Never
  imagePullSecrets:
    - imagepull
  driver:
    labels:
      version: 3.4.1
  executor:
    labels:
      version: 3.4.1
