apiVersion: "sparkoperator.hpe.com/v1beta2"
kind: SparkApplication
metadata:
  name: spark-etl-{{ts_nodash|replace("T", "")}
spec:
  sparkConf:
    spark.hadoop.fs.s3a.path.style.access: "true"
    spark.hadoop.fs.s3a.impl: "org.apache.hadoop.fs.s3a.S3AFileSystem"
    spark.hadoop.fs.s3a.connection.ssl.enabled: "false"
    spark.hadoop.fs.s3a.s3.client.factory.impl: org.apache.hadoop.fs.s3a.NonChunkedDefaultS3ClientFactory
    spark.driver.extraClassPath: /mnt/shared/spark/disable-chunk-encoding-334.jar
    spark.executor.extraClassPath: /mnt/shared/spark/disable-chunk-encoding-334.jar
    spark.hadoop.fs.s3a.bucket.ezua-demo.endpoint: http://local-s3-service.ezdata-system.svc.cluster.local:30000
    spark.ssl.enabled: "false"
    spark.dynamicAllocation.enabled: "true"
    spark.dynamicAllocation.shuffleTracking.enabled: "true"
    spark.dynamicAllocation.minExecutors: "1"
    spark.dynamicAllocation.maxExecutors: "4"
    spark.sql.extensions: "io.delta.sql.DeltaSparkSessionExtension"
    spark.sql.catalog.spark_catalog: "org.apache.spark.sql.delta.catalog.DeltaCatalog"
    spark.executor.extraJavaOptions: "-Dcom.amazonaws.sdk.disableCertChecking=true"
    spark.driver.extraJavaOptions: "-Dcom.amazonaws.sdk.disableCertChecking=true"
    spark.hadoop.fs.s3a.access.key: "PO93KAAP2YTG4RHMG499FENAFWYUH9Q91XOJYQ6UNY4R0XUVY35A53L47"
    spark.hadoop.fs.s3a.secret.key: "UV0H7MFJI96MCFY03IMD9X6ZT8H43B3GDS8SXGA4Z7FH0QT2DSZV3ZCKTHS93Z"
    spark.hadoop.fs.s3a.endpoint: "https://54.251.141.200:9000"
  type: Python
  sparkVersion: 3.4.1
  mode: cluster
  image: "gcr.io/mapr-252711/spark-py-3.4.1:v3.4.1"
  imagePullPolicy: Always
  mainApplicationFile: "local:///mnt/shared/spark_scripts/hive_dataload.py"
  restartPolicy:
    type: Never
  imagePullSecrets:
    - imagepull
  driver:
    cores: 2
    coreLimit: "2000m"
    memory: "1000M"
    labels:
      version: 3.4.1
  executor:
    cores: 2
    coreLimit: "2000m"
    memory: "1000M"
    labels:
      version: 3.4.1